Issues/6 add to metamask button
lira-dao/ecosystem pull request #52
Opened 2024-08-01 15:52 UTC by dev0614

2024-08-01 17:29 UTC, fredev requested changes

2024-08-01 17:29 UTC, fredev commented on apps/dex/.env.testnet
revert the changes to this file

2024-08-01 17:29 UTC, fredev commented on apps/dex/package.json
> +    "dotenv-cli": "^7.4.2"
dotenv-cli is not needed, remove the dependency

2024-08-01 17:29 UTC, fredev commented on apps/dex/src/components/AddTokenToMetamaskButton.tsx
> +  token:
can we use `Currency` for this type?

2024-08-01 17:29 UTC, fredev commented on apps/dex/src/components/Web3Provider.tsx
> +console.log(projectId)
remove console.log

2024-08-01 21:38 UTC, dev0614 commented on apps/dex/src/components/Web3Provider.tsx
> +console.log(projectId)
Will delete the console.

2024-08-01 21:44 UTC, dev0614 commented on apps/dex/src/components/AddTokenToMetamaskButton.tsx
> +  token:
Will fix that

2024-08-01 21:45 UTC, dev0614 commented on apps/dex/package.json
> +    "dotenv-cli": "^7.4.2"
Without dotenv-cli, couldn't import env variables.
If it's not necessary, you can delete it.

2024-08-02 08:19 UTC, fredev approved these changes

2024-08-02 08:19 UTC, merged